language: java
sudo: false
before_install:
  - echo $HOME
  - git clone --depth=50 --branch=master https://github.com/popkit/leap.git popkit/pelpa/leap
script:
  - mvn compile
after_script:
  - ls -a
